#!/bin/bash

PERSON1="Rahim" "No space allowed"
PERSON2="Robert"

echo "$PERSON1 : Hi $PERSON2"
echo "$PERSON2 : Hi $PERSON1"
echo "$PERSON1 : How are you?"
echo "$PERSON2 : I am fine. What about you?"