#!/bin/bash

PERSON1="Nikhil"
PERSON2="Robert"

echo "$PERSON1 : Hi $PERSON2"
echo "$PERSON2 : Hi $PERSON1"
echo "$PERSON1 : How are you?"
echo "$PERSON2 : I am fine. What about you?"

#tried person 1 as Rahim and now trying person 1 as Nikhil